name: gitea
version: 1.3.1
apiVersion: v2
appVersion: 1.11.4
description: Git with a cup of tea
icon: https://docs.gitea.io/images/gitea.png
keywords:
  - git
  - issue tracker
  - code review
  - wiki
  - gitea
  - gogs
sources:
  - https://github.com/go-gitea/gitea
  - https://hub.docker.com/r/gitea/gitea/
maintainers:
  - name: Charlie Drage
    email: charlie@charliedrage.com
