{{- if (not .Values.config.secretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gitea-secret-name" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{ if .Values.config.secretKey }}
  secret-key: {{ .Values.config.secretKey | b64enc }}
  {{ end }}
  {{ if .Values.config.jwtSecret }}
  jwt-secret: {{ .Values.config.jwtSecret | b64enc }}
  {{ end }}
  {{ if .Values.config.lfsJwtSecret }}
  lfs-jwt-secret: {{ .Values.config.lfsJwtSecret | b64enc }}
  {{ end }}
  {{ if .Values.config.internalToken }}
  internal-token: {{ .Values.config.internalToken | b64enc }}
  {{ end }}
{{- end }}