
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gitea.fullname" . }}
  labels:
    app: {{ template "gitea.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "gitea.fullname" . }}
  template: 
    metadata:
      labels:
        app: {{ template "gitea.fullname" . }}
    spec:
      containers:
      {{ include "gitea" . | indent 6 }}
      {{ include "memcached" . | indent 6 }}
      {{- if .Values.affinity }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      initContainers: {{ include "init" . | nindent 6 }}
      volumes:
      - name: gitea-data
      {{- if .Values.persistence.enabled }}
        {{- if .Values.persistence.directGiteaVolumeMount }}
        {{- toYaml .Values.persistence.directGiteaVolumeMount | nindent 8 }}
        {{- else }}
        persistentVolumeClaim:
         claimName: {{ .Values.persistence.existingGiteaClaim | default (include "fullname" .) }}
        {{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: gitea-config
        configMap:
          name: {{ template "gitea.fullname" . }}

      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
