{{- $fullName := include "gitea.fullname" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $fullName }}
  template: 
    metadata:
      labels:
        app: {{ $fullName }}
    spec:
      containers:
      {{ include "gitea" . | indent 6 }}
      {{ include "memcached" . | indent 6 }}
      {{- if .Values.affinity }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      initContainers: {{ include "init" . | nindent 6 }}
      volumes:
      - name: gitea-data
      {{- if .Values.persistence.enabled }}
        {{- if .Values.persistence.directGiteaVolumeMount }}
        {{- toYaml .Values.persistence.directGiteaVolumeMount | nindent 8 }}
        {{- else }}
        persistentVolumeClaim:
         claimName: {{ .Values.persistence.existingGiteaClaim | default $fullName }}
        {{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: gitea-config
        configMap:
          name: {{ $fullName }}
      - name: database-secret
        secret:
          secretName: {{ template "db-secret-name" . }}
          items:
            - key: {{ template "db-secret-key" . }}
              path: db-password
      - name: gitea-secret
        secret:
          secretName: {{ template "gitea-secret-name" . }}

      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
